version: '3.8'

services:
  # =============================================================================
  # Frontend - React Application with Nginx
  # =============================================================================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${FRONTEND_PORT:-8082}:80"
    environment:
      - NODE_ENV=${ENVIRONMENT:-production}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # =============================================================================
  # Backend - Express + Node.js Application
  # =============================================================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "${BACKEND_PORT:-8000}"
    environment:
      - NODE_ENV=${ENVIRONMENT:-production}
      - PORT=${BACKEND_PORT:-8000}
    env_file:
      - ./backend/.env
    volumes:
      - backend-data:/app/data
      - backend-logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# =============================================================================
# Volumes persistentes
# =============================================================================
volumes:
  backend-data:
    driver: local
  backend-logs:
    driver: local

# =============================================================================
# Rede personalizada
# =============================================================================
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 